### ISSUE TITLE
Failed to import on Android Studio

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [mrmike/RenderScriptPlayground#2]
I get this:

Error:(11, 0) Gradle DSL method not found: 'renderscriptSupportMode()'
Possible causes:<ul><li>The project 'RenderScriptPlayground' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>

Also, would be nice to see a tutorial on how to make a project that has RS script.

**Comment by amittomar287** [comment]
Hello ,

Please install the latest plugins and restart Studio

Regards,
Amit

On Wed, Aug 5, 2015 at 4:59 AM, AndroidDeveloperLB <notifications@github.com

**Comment by AndroidDeveloperLB** [comment]
Updated to latest plugins. Now I have this:
![untitled20150813013200](https://cloud.githubusercontent.com/assets/5357526/9238474/30266a20-415b-11e5-9bc3-272758de56c5.png)

**Comment by amittomar287** [comment]
Do R & D It happens sometims but after plugin install it will be resolved after sometime it seems that you are running an old version of Android Studio that's why it is asking for updation you need to update most of the things then error will be resolved soon . 
Also please install or update sdk coz this error is shown only when you are using old gradle file so please update this things

**Comment by AndroidDeveloperLB** [comment]
No, I'm always using the latest version of Android Studio.
I've tried again. This time with Android-Studio 1.4 Preview 2 , and this is what I see:
![untitled20150815222502](https://cloud.githubusercontent.com/assets/5357526/9290442/94701470-439c-11e5-9467-3503e61c30b6.png)

Opening the project again, and I see the same error as I've reported before.

**Comment by amittomar287** [comment]
Hello ,
Please read the link for guidence to migrate you gradle file from older version to newer version :http://tools.android.com/tech-docs/new-build-system/migrating-to-1-0-0 .Hope it will help.

Thanks & Regards,
Amit Singh Tomar

**Comment by AndroidDeveloperLB** [comment]
Nothing I've tried helped. Can you please fix the project?

**Comment by mrmike** [comment]
Hi @AndroidDeveloperLB 
I've just updated gradle and sdk version in the project. There's an issue with loading script for grayscale now but I'll try to fix it later. Everything else should works.

**Comment by AndroidDeveloperLB** [comment]
Now I get this error:

Error:Execution failed for task ':renderscript:compileArmDebugRenderscript'.  com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\android\Sdk\build-tools\23.0.1\llvm-rs-cc.exe'' finished with non-zero exit value -1073741515

Any idea why it occurs? It even occurs when I try to create a project with Renderscript by myself... 

Also, why do you use JNI ? To show how well it performs compared to RS ?

**Comment by mrmike** [comment]
Hi @AndroidDeveloperLB 

I've only added JNI to demonstrate how to use it and it's only used to detect processor type. You can easily remove this part of code and just use this http://developer.android.com/reference/android/os/Build.html#SUPPORTED_ABIS instead.

**Comment by AndroidDeveloperLB** [comment]
SUPPORTED_ABIS requires API 21 .
Also, why do you need it, if Renderscript is supposed to work on previous ones?

The issue I've written about also doesn't have anything to do with JNI. It disappears when using :

buildToolsVersion "22.0.1"

It's probably a bug of Google.

When doing it, it compiles fine. Now that I finally can look at the code, I'd like to also ask this:
where is the part you use your own RS script itself? I've ran the app, and I see blurry image, yet the script says "greyscale". ...

**Comment by mrmike** [comment]
@AndroidDeveloperLB 
Greyscale happens when you click on menu button, see `loadMonoScript` in `MainActivity.java`. But like I said it before it's not working after changing sdk versions.

**Comment by AndroidDeveloperLB** [comment]
oh. for some reason it shows a transparent menu item (didn't know it's even
possible).
you should have put a button instead, as there is no action bar.

**Comment by mrmike** [comment]
When I'll have a bit more spare time I'll try to fix it.

Can I help you with something else?

**Comment by AndroidDeveloperLB** [comment]
I'm only starting to learn about Renderscript. If you have a nice tutorial,
this would be great.
Do note that currently your app won't work because of what I wrote.

**Comment by mrmike** [comment]
Hi @AndroidDeveloperLB 
Check out this links:
- http://developer.android.com/guide/topics/renderscript/index.html
- https://software.intel.com/en-us/articles/renderscript-basic-sample-for-android-os
- http://code.tutsplus.com/tutorials/getting-started-with-renderscript-on-android--mobile-9154

**Comment by AndroidDeveloperLB** [comment]
nice . thank you !

**Comment by AndroidDeveloperLB** [comment]
I'm actually making a presentation. Any suggestion what topics to cover?

**Comment by amittomar287** [comment]
you can take "Marshmallow" Version for Presentation because its a very new
version many of them are unknown .
If presentation is of Android Related .
IF it is for other stream then you can use "climate change" coz it is a hot
topic nowadays. :)

Thanks & Regards,
Amit Singh Tomar

On Fri, Oct 2, 2015 at 9:23 AM, AndroidDeveloperLB <notifications@github.com

**Comment by AndroidDeveloperLB** [comment]
What do you mean "Marshmallow" Version ? There are some new stuff regarding RS in Android 6 ? 
If so, can you show a link?

**Comment by amittomar287** [comment]
This is the link of Youtube channel where you can see videos of Android latest version "Marshmallow" i.e. 6.0 or above  so 
https://www.youtube.com/user/androiddevelopers 

you can see the videos and know more about this version and can do demonstration

**Comment by AndroidDeveloperLB** [comment]
I don't remember watching there anything that's about RS.

**Comment by amittomar287** [comment]
it is related to Android Versions not related to RS .

**Comment by AndroidDeveloperLB** [comment]
The presentation is about RS...

**Comment by amittomar287** [comment]
Hey mrmike/RenderScriptP,

Discover high quality jobs and connect with recruiters on LinkedIn.

- Amit Singh

Accept invite: https://www.linkedin.com/e/v2?e=0-img6gggq-44&t=ssuw&ek=invite_guest&li=14&m=invite_guest&ts=india_a&sharedKey=FbHdqkFE&invitationId=6121261455867199488

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-img6gggq-44&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEXYMBQMuqSjgAAAVPMXEQAkDv4_c-nXq7sp7_yie-m7wep76kMCQS0Bb3ruQlduu8mNqdJnyaRssyQK70c9FLt7O-c1KGGl0vhTzfapJ9bp2ztPxGRxBzwhZrfZTlIwT0_9An9irWvaBhyugihAInyudP9N9LFlUr01rHbrAoStg07xBNh35EXlQYYxlFHpr1y&eid=0-img6gggq-44

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-img6gggq-44&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by AndroidDeveloperLB** [comment]
???

**Comment by amittomar287** [comment]
Hey mrmike/RenderScriptP,

Discover high quality jobs and connect with recruiters on LinkedIn.

- Amit Singh

Accept invite: https://www.linkedin.com/e/v2?e=0-img6ggyo-ul&t=ssuw&ek=invite_guest&li=14&m=invite_guest&ts=india_a&sharedKey=0yKMcC2k&invitationId=6121261454491475968

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-img6ggyo-ul&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGXqY4tpisEUQAAAVPMYf0kdYsCICcWyn7zYEJh4RmXridqbBaMSiGT8NgUK6VGP8U5JwMS2hpPc8hpicxF5yZfuIZwQXvEa6RQdHaiMAQHz6A9yX5d7sgtdbI5JEEuk-iqHkD8rQoIQpQh0fY9bFHte2mYHIvtKTFr6V1ZrjNjmmTQgfFJ1QQQR8hs7PmejI69&eid=0-img6ggyo-ul

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-img6ggyo-ul&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by AndroidDeveloperLB** [comment]
What is going on?!

**Comment by amittomar287** [comment]
Amit Singh Tomar would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-nlukrg-imol8i35-s3&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=FbHdqkFE&invitationID=6121261455867199488

View Amit Singh Tomar&#39;s profile: https://www.linkedin.com/e/v2?e=-nlukrg-imol8i35-s3&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=FbHdqkFE&invitationID=6121261455867199488

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-nlukrg-imol8i35-s3&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-nlukrg-imol8i35-s3&loid=AQGaVGRiqIThtgAAAVPrPp9a0uZ06XHn_Sp4Ot2inkAJejG_9G9c-nDW158mlN3MnpNXJK_hVrSkjJJH_6BUrsZ4LsC1Z_OG-q-OdG7guaupHPz1stTLV5uCzpXUajMi1Z7fk64QRmg6uRVTULI0Qi9VtpVXMvGC_8RCmGP13U7hG0YksqA_PNWAqGkVRZJttyAF

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-nlukrg-imol8i35-s3&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by amittomar287** [comment]
Amit Singh Tomar would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=a275bi-imol7p0p-ip&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=0yKMcC2k&invitationID=6121261454491475968

View Amit Singh Tomar&#39;s profile: https://www.linkedin.com/e/v2?e=a275bi-imol7p0p-ip&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=0yKMcC2k&invitationID=6121261454491475968

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=a275bi-imol7p0p-ip&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=a275bi-imol7p0p-ip&loid=AQFHYq_USJCdUAAAAVPrSNgKb203AyMPBcgc_bCjwt81hbq7TnH3czHfpzzb07OZOuQpKOdxexs88sMlT8KqIwKa3Eqx-oR2GY1KEvhCERB648uiDriumoXFnlpczZIK755HbIaKMq-d_9SgIOb7waO9Zp7r1RSCMgu0EJpKlLMnK4C7bYzm0lLadF3A8X3gmUmI

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=a275bi-imol7p0p-ip&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by amittomar287** [comment]
Amit Singh Tomar would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=a275bi-imyldx73-sq&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=0yKMcC2k&invitationID=6121261454491475968

View Amit Singh Tomar&#39;s profile: https://www.linkedin.com/e/v2?e=a275bi-imyldx73-sq&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=0yKMcC2k&invitationID=6121261454491475968

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=a275bi-imyldx73-sq&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=a275bi-imyldx73-sq&loid=AQGxqKbPi0tgwgAAAVQPSZXTRIzL-p2dh7zAKEWb0tx73pJ1Zb7WK4sJZ1WQSg_bEhSNGrz3fVXUbUAZ2jl-OTY4mWtG-B4CO8pUwtHus05wYg_tzYoP4eLKvZhkLMroD6CvOvJRgWVwwCnINfoVqahUfbHtWeZWZe6T2h-yMjmNNfbPFckufsCnjSpnqwZAVbgY

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=a275bi-imyldx73-sq&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by amittomar287** [comment]
Amit Singh Tomar would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-nlukrg-imylgobv-4k&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=FbHdqkFE&invitationID=6121261455867199488

View Amit Singh Tomar&#39;s profile: https://www.linkedin.com/e/v2?e=-nlukrg-imylgobv-4k&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=FbHdqkFE&invitationID=6121261455867199488

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-nlukrg-imylgobv-4k&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-nlukrg-imylgobv-4k&loid=AQHRE-fl_67vnQAAAVQPSbL3vSQXGz3gWg5bqDyCZ0NTioGiD5a33PkNiYQkD6SYU4z9ooH-llIG-esM8CtvDHCa8iZpOR-OHpaQIl0Phm9vbA8INh-R4jp34qdQIEtNym2CVEHRYcNMyXf1xmML8cszGqHS8IuOM9CaEArwhZDixu7llyZ2AdBcRX1IeVt4gUSA

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-nlukrg-imylgobv-4k&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
